/**
 * VulnShop — Interactive Setup Script
 * Handles MySQL credentials automatically, creates DB, seeds data, starts server.
 * Run: node setup.js
 */

const mysql  = require('mysql2/promise');
const fs     = require('fs');
const path   = require('path');
const readline = require('readline');

// ── Colour helpers ────────────────────────────────────────────
const c = {
  reset : '\x1b[0m',
  bright: '\x1b[1m',
  red   : '\x1b[31m',
  green : '\x1b[32m',
  yellow: '\x1b[33m',
  cyan  : '\x1b[36m',
  orange: '\x1b[33m',
};
const log  = (msg)       => console.log(msg);
const ok   = (msg)       => console.log(`${c.green}✅ ${msg}${c.reset}`);
const err  = (msg)       => console.log(`${c.red}❌ ${msg}${c.reset}`);
const warn = (msg)       => console.log(`${c.yellow}⚠️  ${msg}${c.reset}`);
const info = (msg)       => console.log(`${c.cyan}ℹ️  ${msg}${c.reset}`);
const bold = (msg)       => `${c.bright}${msg}${c.reset}`;

// ── Banner ────────────────────────────────────────────────────
function banner() {
  console.log(`
${c.orange}╔══════════════════════════════════════════════════════╗
║        🛒  VulnShop — Auto Setup & Launcher         ║
╚══════════════════════════════════════════════════════╝${c.reset}
`);
}

// ── Prompt helper ─────────────────────────────────────────────
function prompt(question, defaultVal = '') {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => {
    const displayDefault = defaultVal !== '' ? ` [${defaultVal}]` : '';
    rl.question(`${c.cyan}${question}${displayDefault}: ${c.reset}`, answer => {
      rl.close();
      resolve(answer.trim() || defaultVal);
    });
  });
}

function promptPassword(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => {
    // Hide input on terminals that support it
    if (process.stdout.isTTY) {
      process.stdout.write(`${c.cyan}${question}: ${c.reset}`);
      process.stdin.setRawMode(true);
      let pwd = '';
      process.stdin.resume();
      process.stdin.setEncoding('utf8');
      process.stdin.on('data', function handler(ch) {
        ch = ch.toString();
        if (ch === '\n' || ch === '\r' || ch === '\u0003') {
          process.stdin.setRawMode(false);
          process.stdin.pause();
          process.stdin.removeListener('data', handler);
          process.stdout.write('\n');
          rl.close();
          resolve(pwd);
        } else if (ch === '\u007f') {
          pwd = pwd.slice(0, -1);
        } else {
          pwd += ch;
          process.stdout.write('*');
        }
      });
    } else {
      rl.question(`${c.cyan}${question}: ${c.reset}`, answer => {
        rl.close();
        resolve(answer.trim());
      });
    }
  });
}

// ── Try connecting with given credentials ─────────────────────
async function tryConnect(host, port, user, password) {
  try {
    const conn = await mysql.createConnection({ host, port: parseInt(port), user, password, connectTimeout: 5000 });
    await conn.ping();
    await conn.end();
    return true;
  } catch {
    return false;
  }
}

// ── Auto-detect credentials ───────────────────────────────────
async function autoDetect(host, port) {
  const candidates = [
    { user: 'root', password: ''           },
    { user: 'root', password: 'root'       },
    { user: 'root', password: 'mysql'      },
    { user: 'root', password: 'password'   },
    { user: 'root', password: 'admin'      },
    { user: 'root', password: '123456'     },
    { user: 'root', password: 'vulnshop_pass' },
    { user: 'root', password: 'toor'       },
  ];

  info('Trying common MySQL credentials automatically...');
  for (const cred of candidates) {
    const passDisplay = cred.password === '' ? '(blank)' : `"${cred.password}"`;
    process.stdout.write(`   Testing ${bold(cred.user)} / ${passDisplay} ... `);
    const ok2 = await tryConnect(host, port, cred.user, cred.password);
    if (ok2) {
      console.log(`${c.green}✅ Connected!${c.reset}`);
      return cred;
    }
    console.log(`${c.red}✗${c.reset}`);
  }
  return null;
}

// ── Write .env file ───────────────────────────────────────────
function writeEnv(cfg) {
  const content = `# VulnShop Environment — auto-generated by setup.js
PORT=${cfg.port || 3000}
NODE_ENV=development

DB_HOST=${cfg.dbHost}
DB_PORT=${cfg.dbPort}
DB_USER=${cfg.dbUser}
DB_PASSWORD=${cfg.dbPassword}
DB_NAME=vulnshop

SESSION_SECRET=vulnshop-super-secret-key-2024
`;
  fs.writeFileSync(path.join(__dirname, '.env'), content);
  ok('.env file written');
}

// ── Run SQL file ──────────────────────────────────────────────
async function runSQL(conn) {
  const sqlFile = path.join(__dirname, 'database', 'init.sql');
  if (!fs.existsSync(sqlFile)) {
    throw new Error(`init.sql not found at: ${sqlFile}`);
  }

  const raw = fs.readFileSync(sqlFile, 'utf8');

  // Split on semicolons but skip empty statements and comments
  const statements = raw
    .split(';')
    .map(s => s.trim())
    .filter(s => s.length > 0 && !s.startsWith('--'));

  let count = 0;
  for (const stmt of statements) {
    try {
      await conn.query(stmt);
      count++;
    } catch (e) {
      // Ignore "table already exists" and "unknown table" during DROP
      if (!e.message.includes('already exists') &&
          !e.message.includes('Unknown table') &&
          !e.message.includes("Can't DROP")) {
        warn(`Statement skipped: ${e.message.slice(0, 80)}`);
      }
    }
  }
  return count;
}

// ── Main ──────────────────────────────────────────────────────
async function main() {
  banner();

  // Step 1: Get host/port
  log(bold('── Step 1: MySQL Server Location ─────────────────────\n'));
  const dbHost = await prompt('MySQL host', 'localhost');
  const dbPort = await prompt('MySQL port', '3306');

  // Step 2: Try auto-detect
  log(`\n${bold('── Step 2: Credentials ────────────────────────────────')}\n`);
  let dbUser, dbPassword;

  const detected = await autoDetect(dbHost, dbPort);

  if (detected) {
    dbUser     = detected.user;
    dbPassword = detected.password;
    ok(`Auto-detected: user="${dbUser}" password="${dbPassword === '' ? '(blank)' : dbPassword}"`);
  } else {
    warn('Could not auto-detect credentials. Please enter them manually.');
    dbUser     = await prompt('MySQL username', 'root');
    dbPassword = await promptPassword('MySQL password (hidden)');

    const works = await tryConnect(dbHost, dbPort, dbUser, dbPassword);
    if (!works) {
      err('Connection failed with those credentials.');
      log('\nTroubleshooting tips:');
      log('  1. Make sure MySQL / XAMPP / WAMP is running');
      log('  2. Check your MySQL username and password');
      log('  3. Try opening phpMyAdmin and use those same credentials');
      log('  4. Or import database/init.sql manually via phpMyAdmin\n');
      process.exit(1);
    }
    ok('Connection successful!');
  }

  // Step 3: Server port
  log(`\n${bold('── Step 3: App Port ───────────────────────────────────')}\n`);
  const appPort = await prompt('VulnShop server port', '3000');

  // Step 4: Write .env
  log(`\n${bold('── Step 4: Writing Configuration ──────────────────────')}\n`);
  writeEnv({ dbHost, dbPort, dbUser, dbPassword, port: appPort });

  // Step 5: Create database + run SQL
  log(`\n${bold('── Step 5: Initializing Database ──────────────────────')}\n`);

  let conn;
  try {
    conn = await mysql.createConnection({
      host              : dbHost,
      port              : parseInt(dbPort),
      user              : dbUser,
      password          : dbPassword,
      multipleStatements: true,
      connectTimeout    : 10000,
    });
    ok('Connected to MySQL');

    // Create DB
    await conn.query('CREATE DATABASE IF NOT EXISTS vulnshop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
    ok('Database "vulnshop" ready');

    await conn.query('USE vulnshop');

    info('Running schema + seed data (this takes a few seconds)...');
    const sqlFile = path.join(__dirname, 'database', 'init.sql');
    const raw = fs.readFileSync(sqlFile, 'utf8');
    await conn.query(raw);
    ok('Schema and seed data loaded');

    // Verify
    const [rows] = await conn.query('SELECT COUNT(*) AS n FROM products');
    ok(`Products seeded: ${rows[0].n}`);
    const [urows] = await conn.query('SELECT COUNT(*) AS n FROM users');
    ok(`Users seeded: ${urows[0].n}`);
    const [frows] = await conn.query('SELECT COUNT(*) AS n FROM flags');
    ok(`Flags seeded: ${frows[0].n}`);

    await conn.end();
  } catch (e) {
    err(`Database error: ${e.message}`);
    if (conn) await conn.end().catch(() => {});
    process.exit(1);
  }

  // Step 6: Summary
  log(`
${c.green}${c.bright}╔══════════════════════════════════════════════════════╗
║              🎉  Setup Complete!                     ║
╠══════════════════════════════════════════════════════╣
║                                                      ║
║  Start the app:   node server.js                     ║
║  Open browser:    http://localhost:${String(appPort).padEnd(25)}║
║                                                      ║
║  Admin login:     admin / admin123                   ║
║  User login:      john_doe / password123             ║
║                                                      ║
║  Challenges:      http://localhost:${String(appPort).padEnd(25)}║
║                   /api/challenges                    ║
║                                                      ║
╚══════════════════════════════════════════════════════╝${c.reset}
`);

  // Step 7: Offer to start server
  const startNow = await prompt('Start VulnShop server now? (y/n)', 'y');
  if (startNow.toLowerCase() === 'y') {
    log(`\n${c.cyan}Starting server...${c.reset}\n`);
    // Re-load env and start
    require('dotenv').config();
    require('./server.js');
  } else {
    log(`\nRun ${bold('node server.js')} whenever you're ready.\n`);
    process.exit(0);
  }
}

main().catch(e => {
  err(`Unexpected error: ${e.message}`);
  process.exit(1);
});
